"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
type RecordItem = { uid: string; [key: string]: any };
export default function MerchantKycPage() {
  const [items, setItems] = useState<RecordItem[]>([]); const [selected, setSelected] = useState<RecordItem | null>(null);
  const load = async () => { const response = await api.get<{ users: RecordItem[] }>("/admin/merchant-onboarding"); setItems(response.data.users ?? []); };
  useEffect(() => { void load(); }, []);
  const action = async (uid: string, path: string, body?: object) => { await api.post(`/admin/merchant-onboarding/${uid}/${path}`, body); await load(); };
  const reject = async (uid: string) => { const reason = window.prompt("Enter rejection reason"); if (reason?.trim()) await action(uid, "reject", { reason: reason.trim() }); };
  const view = async (uid: string) => { const [details, documents] = await Promise.all([api.get(`/admin/merchant-onboarding/${uid}`), api.get(`/admin/merchant-onboarding/${uid}/documents`)]); setSelected({ ...details.data, documents: documents.data.documents ?? [] }); };
  const openDocument = async (objectKey: string) => { const response = await api.get('/admin/kyc/document', { params: { objectKey }, responseType: 'blob' }); const url = URL.createObjectURL(response.data); window.open(url, '_blank', 'noopener,noreferrer'); setTimeout(() => URL.revokeObjectURL(url), 60000); };
  return <main className="p-8"><h1 className="text-3xl font-bold">Merchant KYC</h1><div className="mt-8 overflow-x-auto rounded-xl bg-white shadow"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Merchant</th><th className="p-4">KYC</th><th className="p-4">Settlement</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.uid} className="border-b"><td className="p-4">{item.legalBusinessName ?? item.uid}</td><td className="p-4">{item.kycStatus ?? "NOT_STARTED"}</td><td className="p-4">{item.settlementStatus ?? "NOT_CONFIGURED"}</td><td className="flex flex-wrap gap-2 p-4"><button className="rounded bg-gray-700 px-3 py-2 text-white" onClick={() => view(item.uid)}>View</button><button disabled={item.kycStatus === "VERIFIED"} className="rounded bg-green-600 px-3 py-2 text-white disabled:opacity-50" onClick={() => action(item.uid, "verify")}>Verify</button><button disabled={item.kycStatus !== "VERIFIED" || Boolean(item.razorpayLinkedAccountId)} className="rounded bg-blue-600 px-3 py-2 text-white disabled:opacity-50" onClick={() => action(item.uid, "create-linked-account")}>Create Route</button><button disabled={item.linkedAccountStatus !== "CREATED" || item.settlementStatus === "ACTIVE"} className="rounded bg-purple-600 px-3 py-2 text-white disabled:opacity-50" onClick={() => action(item.uid, "activate-settlement")}>Activate</button><button disabled={item.kycStatus === "VERIFIED"} className="rounded bg-red-600 px-3 py-2 text-white disabled:opacity-50" onClick={() => reject(item.uid)}>Reject</button></td></tr>)}</tbody></table></div>{selected && <section className="mt-6 rounded-xl bg-white p-6 shadow"><div className="flex justify-between"><h2 className="text-xl font-bold">{selected.legalBusinessName ?? selected.uid}</h2><button onClick={() => setSelected(null)}>Close</button></div><p className="mt-2">Owner: {selected.ownerName ?? "-"} · Business: {selected.businessType ?? "-"} · KYC: {selected.kycStatus ?? "-"}</p><h3 className="mt-6 font-semibold">Documents</h3>{(selected.documents ?? []).map((document: any) => <div key={`${document.type}-${document.objectKey}`} className="flex items-center justify-between border-b py-3"><span>{document.type} — {document.originalName} ({document.status})</span><button className="rounded bg-gray-700 px-3 py-2 text-white" onClick={() => openDocument(document.objectKey)}>View</button></div>)}</section>}</main>;
}
