import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { FirebaseService } from '../firebase/firebase.service.js';
import { RazorpayPayoutService } from '../settlements/razorpay-payout.service.js';
import { RazorpayRouteService } from '../settlements/razorpay-route.service.js';

@Injectable()
export class OnboardingService {
  constructor(private readonly firebase: FirebaseService, private readonly route: RazorpayRouteService, private readonly payout: RazorpayPayoutService) {}
  private collection(role: 'MERCHANT' | 'DELIVERY') { return role === 'MERCHANT' ? 'merchantOnboarding' : 'deliveryOnboarding'; }
  private async user(uid: string) { const ref = this.firebase.getFirestore().collection('users').doc(uid); const snapshot = await ref.get(); if (!snapshot.exists) throw new NotFoundException('User not found'); return { ref, data: snapshot.data() ?? {} }; }
  async get(uid: string, role: 'MERCHANT' | 'DELIVERY') { const { data } = await this.user(uid); return { success: true, onboarding: this.mask(data[this.collection(role)] ?? { approvalStatus: 'PENDING', kycStatus: 'NOT_STARTED', settlementStatus: role === 'MERCHANT' ? 'NOT_CONFIGURED' : undefined }) }; }
  async update(uid: string, role: 'MERCHANT' | 'DELIVERY', body: Record<string, unknown>) { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; if (current.kycStatus === 'VERIFIED') throw new ForbiddenException('Verified onboarding cannot be edited'); const allowed = role === 'MERCHANT' ? ['legalBusinessName', 'customerFacingBusinessName', 'businessType', 'ownerName', 'phone', 'email', 'registeredAddress', 'panNumber', 'gstin', 'fssaiNumber', 'fssaiExpiryDate', 'bank'] : ['legalName', 'dateOfBirth', 'phone', 'email', 'address', 'panNumber', 'vehicleType', 'vehicleNumber', 'drivingLicenceNumber', 'drivingLicenceExpiry', 'insuranceExpiry', 'bank', 'upiId']; const safe = Object.fromEntries(Object.entries(body).filter(([field]) => allowed.includes(field))); const onboarding = { ...current, ...safe, updatedAt: new Date().toISOString() }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  async submit(uid: string, role: 'MERCHANT' | 'DELIVERY') { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; if (!current || Object.keys(current).length === 0) throw new BadRequestException('Complete onboarding details before submitting'); const onboarding = { ...current, kycStatus: 'SUBMITTED', approvalStatus: current.approvalStatus ?? 'PENDING', submittedAt: new Date().toISOString() }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  async addDocument(uid: string, role: 'MERCHANT' | 'DELIVERY', document: Record<string, unknown>) { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; if (current.kycStatus === 'VERIFIED') throw new ForbiddenException('Verified onboarding cannot be edited'); const documents = [...(current.documents ?? []), { ...document, status: 'PENDING', createdAt: new Date().toISOString() }]; await ref.set({ [key]: { ...current, documents } }, { merge: true }); return { success: true, onboarding: this.mask({ ...current, documents }) }; }
  async list(role: 'MERCHANT' | 'DELIVERY') { const snapshot = await this.firebase.getFirestore().collection('users').where('role', '==', role).get(); return { success: true, users: snapshot.docs.map((doc) => ({ uid: doc.id, ...this.mask((doc.data() as any)[this.collection(role)] ?? {}) })) }; }
  async getAdmin(uid: string, role: 'MERCHANT' | 'DELIVERY') { const result = await this.get(uid, role); return { ...result, uid }; }
  async verify(uid: string, role: 'MERCHANT' | 'DELIVERY') { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; const onboarding = { ...current, approvalStatus: 'APPROVED', kycStatus: 'VERIFIED', ...(role === 'MERCHANT' ? { settlementStatus: 'NOT_CONFIGURED' } : { payoutStatus: current.payoutStatus ?? 'NOT_CONFIGURED' }), verifiedAt: new Date().toISOString() }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  async reject(uid: string, role: 'MERCHANT' | 'DELIVERY', reason?: string) { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; const onboarding = { ...current, approvalStatus: 'REJECTED', kycStatus: 'REJECTED', rejectionReason: reason?.trim() ?? 'Rejected by administrator' }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  async createLinkedAccount(uid: string) { const { ref, data } = await this.user(uid); const onboarding = (data.merchantOnboarding ?? {}) as any; if (onboarding.kycStatus !== 'VERIFIED') throw new BadRequestException('Merchant KYC must be verified first'); const result = await this.route.createLinkedAccount({ uid, email: onboarding.email ?? data.email ?? '', phone: onboarding.phone ?? data.phoneNumber ?? '', legalBusinessName: onboarding.legalBusinessName ?? '', customerFacingBusinessName: onboarding.customerFacingBusinessName ?? onboarding.legalBusinessName ?? '', businessType: onboarding.businessType ?? 'PROPRIETORSHIP' }); const updated = { ...onboarding, settlementStatus: 'PENDING', razorpayLinkedAccountId: result.id, linkedAccountStatus: 'CREATED' }; await ref.set({ merchantOnboarding: updated }, { merge: true }); const stores = await this.firebase.getFirestore().collection('stores').where('merchantId', '==', uid).get(); await Promise.all(stores.docs.map((store) => store.ref.set({ settlement: { razorpayLinkedAccountId: result.id, linkedAccountStatus: 'CREATED', settlementStatus: 'PENDING', settlementEnabled: false } }, { merge: true }))); return { success: true, account: { id: result.id, status: 'CREATED' } }; }
  async setupDeliveryPayout(uid: string) { const { ref, data } = await this.user(uid); const onboarding = (data.deliveryOnboarding ?? {}) as any; if (onboarding.kycStatus !== 'VERIFIED') throw new BadRequestException('Delivery KYC must be verified first'); if (!onboarding.bank?.accountNumber || !onboarding.bank?.ifsc) throw new BadRequestException('Bank details are required'); const contact = await this.payout.createContact({ name: onboarding.legalName ?? data.name ?? 'Delivery Partner', email: onboarding.email ?? data.email, phone: onboarding.phone ?? data.phoneNumber ?? '', referenceId: uid }); const fund = await this.payout.createBankFundAccount({ contactId: contact.id, accountHolderName: onboarding.bank.beneficiaryName ?? onboarding.legalName ?? '', ifsc: onboarding.bank.ifsc, accountNumber: onboarding.bank.accountNumber }); await ref.set({ deliveryOnboarding: { ...onboarding, razorpayContactId: contact.id, razorpayFundAccountId: fund.id, payoutStatus: 'ACTIVE' } }, { merge: true }); return { success: true, payout: { contactId: contact.id, fundAccountId: fund.id, status: 'ACTIVE' } }; }
  private mask(value: any): any { if (!value || typeof value !== 'object') return value; if (Array.isArray(value)) return value.map((item) => this.mask(item)); const result: Record<string, any> = {}; for (const [key, item] of Object.entries(value)) { if (['accountNumber', 'panNumber', 'aadhaarNumber'].includes(key) && typeof item === 'string') result[key] = item.length <= 4 ? item : `****${item.slice(-4)}`; else if (key === 'bank' && item && typeof item === 'object') result[key] = this.mask(item); else result[key] = this.mask(item); } return result; }
}
