import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { FirebaseService } from '../firebase/firebase.service.js';
import { RazorpayPayoutService } from '../settlements/razorpay-payout.service.js';
import { RazorpayRouteService } from '../settlements/razorpay-route.service.js';

@Injectable()
export class OnboardingService {
  constructor(private readonly firebase: FirebaseService, private readonly route: RazorpayRouteService, private readonly payout: RazorpayPayoutService) {}
  private collection(role: 'MERCHANT' | 'DELIVERY') { return role === 'MERCHANT' ? 'merchantOnboarding' : 'deliveryOnboarding'; }
  private async user(uid: string) { const ref = this.firebase.getFirestore().collection('users').doc(uid); const snapshot = await ref.get(); if (!snapshot.exists) throw new NotFoundException('User not found'); return { ref, data: snapshot.data() ?? {} }; }
  private sanitizeMerchantUpdate(body: Record<string, unknown>) { const allowed = ['legalBusinessName', 'customerFacingBusinessName', 'businessType', 'ownerName', 'phone', 'email', 'registeredAddress', 'panNumber', 'gstin', 'fssaiNumber', 'fssaiExpiryDate', 'bank', 'vehicleType']; return Object.fromEntries(Object.entries(body).filter(([key]) => allowed.includes(key))); }
  private sanitizeDeliveryUpdate(body: Record<string, unknown>) { const allowed = ['legalName', 'dateOfBirth', 'phone', 'email', 'address', 'panNumber', 'vehicleType', 'vehicleNumber', 'drivingLicenceNumber', 'drivingLicenceExpiry', 'insuranceExpiry', 'bank', 'upiId']; return Object.fromEntries(Object.entries(body).filter(([key]) => allowed.includes(key))); }
  async get(uid: string, role: 'MERCHANT' | 'DELIVERY') { const { data } = await this.user(uid); const value = data[this.collection(role)] ?? { approvalStatus: 'PENDING', kycStatus: 'NOT_STARTED', ...(role === 'MERCHANT' ? { settlementStatus: 'NOT_CONFIGURED' } : { payoutStatus: 'NOT_CONFIGURED' }) }; return { success: true, onboarding: this.mask(value) }; }
  async update(uid: string, role: 'MERCHANT' | 'DELIVERY', body: Record<string, unknown>) { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; if (current.kycStatus === 'VERIFIED') throw new ForbiddenException('Verified onboarding cannot be edited'); const safeBody = role === 'MERCHANT' ? this.sanitizeMerchantUpdate(body) : this.sanitizeDeliveryUpdate(body); const onboarding = { ...current, ...safeBody, kycStatus: current.kycStatus ?? 'NOT_STARTED', approvalStatus: current.approvalStatus ?? 'PENDING', updatedAt: new Date().toISOString() }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  private validateSubmission(role: 'MERCHANT' | 'DELIVERY', current: Record<string, any>) {
    const required = role === 'MERCHANT'
      ? ['legalBusinessName', 'ownerName', 'businessType', 'phone', 'registeredAddress', 'panNumber', 'fssaiNumber']
      : ['legalName', 'phone', 'address', 'vehicleType'];
    for (const field of required) if (!current[field]?.toString().trim()) throw new BadRequestException(`${field} is required`);
    if (!current.bank?.beneficiaryName || !current.bank?.accountNumber || !current.bank?.ifsc) throw new BadRequestException('Complete bank details are required');
    if (role === 'DELIVERY' && ['BIKE', 'SCOOTER', 'CAR'].includes(current.vehicleType) && (!current.drivingLicenceNumber || !current.vehicleNumber)) throw new BadRequestException('Driving licence and vehicle registration are required');
  }
  async submit(uid: string, role: 'MERCHANT' | 'DELIVERY') { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; this.validateSubmission(role, current); const now = new Date().toISOString(); const onboarding = { ...current, kycStatus: 'SUBMITTED', approvalStatus: 'PENDING', submittedAt: now, updatedAt: now }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  async addDocument(uid: string, role: 'MERCHANT' | 'DELIVERY', document: Record<string, unknown>) { const allowed = role === 'MERCHANT' ? ['PAN', 'GST', 'FSSAI', 'BANK_PROOF', 'BUSINESS_PROOF', 'TRADE_LICENSE'] : ['PROFILE_PHOTO', 'IDENTITY_PROOF', 'PAN', 'DRIVING_LICENCE', 'RC', 'INSURANCE', 'BANK_PROOF']; const type = String(document.type ?? '').toUpperCase(); if (!allowed.includes(type)) throw new BadRequestException('Unsupported document type'); const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; if (current.kycStatus === 'VERIFIED') throw new ForbiddenException('Verified onboarding cannot be edited'); const documents = [...(current.documents ?? []), { type, objectKey: document.objectKey, originalName: document.originalName, mimeType: document.mimeType, status: 'PENDING', createdAt: new Date().toISOString() }]; const onboarding = { ...current, documents, updatedAt: new Date().toISOString() }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  async list(role: 'MERCHANT' | 'DELIVERY') { const snapshot = await this.firebase.getFirestore().collection('users').where('role', '==', role).get(); return { success: true, users: snapshot.docs.map((doc) => ({ uid: doc.id, ...this.mask((doc.data() as any)[this.collection(role)] ?? {}) })) }; }
  async getAdmin(uid: string, role: 'MERCHANT' | 'DELIVERY') { return { ...(await this.get(uid, role)), uid }; }
  async verify(uid: string, role: 'MERCHANT' | 'DELIVERY') { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; const now = new Date().toISOString(); const onboarding = { ...current, approvalStatus: 'APPROVED', kycStatus: 'VERIFIED', ...(role === 'MERCHANT' ? { settlementStatus: current.settlementStatus ?? 'NOT_CONFIGURED', linkedAccountStatus: current.linkedAccountStatus ?? 'NOT_CREATED' } : { payoutStatus: current.payoutStatus ?? 'NOT_CONFIGURED' }), verifiedAt: now, updatedAt: now }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  async reject(uid: string, role: 'MERCHANT' | 'DELIVERY', reason?: string) { const { ref, data } = await this.user(uid); const key = this.collection(role); const current = (data[key] ?? {}) as Record<string, any>; const onboarding = { ...current, approvalStatus: 'REJECTED', kycStatus: 'REJECTED', rejectionReason: reason?.trim() || 'Rejected by administrator', updatedAt: new Date().toISOString() }; await ref.set({ [key]: onboarding }, { merge: true }); return { success: true, onboarding: this.mask(onboarding) }; }
  private mapBusinessType(value?: string) { switch (value?.trim().toUpperCase()) { case 'PROPRIETORSHIP': return 'proprietorship'; case 'PARTNERSHIP': return 'partnership'; case 'PRIVATE_LIMITED': return 'private_limited'; case 'LLP': return 'llp'; default: throw new BadRequestException('Unsupported business type for Razorpay Route'); } }
  async createLinkedAccount(uid: string) { const { ref: userRef, data } = await this.user(uid); const onboarding = (data.merchantOnboarding ?? {}) as Record<string, any>; if (onboarding.kycStatus !== 'VERIFIED') throw new BadRequestException('Merchant KYC must be verified first'); const db = this.firebase.getFirestore(); const stores = await db.collection('stores').where('merchantId', '==', uid).limit(1).get(); if (stores.empty) throw new BadRequestException('Merchant store not found'); const result = await this.route.createLinkedAccount({ uid, email: onboarding.email ?? data.email ?? '', phone: onboarding.phone ?? data.phoneNumber ?? '', legalBusinessName: onboarding.legalBusinessName ?? '', customerFacingBusinessName: onboarding.customerFacingBusinessName ?? onboarding.legalBusinessName ?? '', businessType: this.mapBusinessType(onboarding.businessType) }); const accountId = result.id?.toString(); if (!accountId) throw new BadRequestException('Razorpay linked account ID missing'); const now = new Date().toISOString(); await Promise.all([userRef.set({ merchantOnboarding: { ...onboarding, razorpayLinkedAccountId: accountId, linkedAccountStatus: 'CREATED', settlementStatus: 'PENDING', updatedAt: now } }, { merge: true }), stores.docs[0].ref.set({ settlement: { razorpayLinkedAccountId: accountId, linkedAccountStatus: 'CREATED', settlementStatus: 'PENDING', settlementEnabled: false, updatedAt: now } }, { merge: true })]); return { success: true, account: { id: accountId, status: 'CREATED' } }; }
  async activateMerchantSettlement(uid: string) { const { ref: userRef, data } = await this.user(uid); const onboarding = (data.merchantOnboarding ?? {}) as Record<string, any>; if (onboarding.approvalStatus !== 'APPROVED' || onboarding.kycStatus !== 'VERIFIED') throw new BadRequestException('Merchant KYC must be verified first'); if (!onboarding.razorpayLinkedAccountId) throw new BadRequestException('Linked account has not been created'); const stores = await this.firebase.getFirestore().collection('stores').where('merchantId', '==', uid).limit(1).get(); if (stores.empty) throw new BadRequestException('Store not found'); const now = new Date().toISOString(); await Promise.all([userRef.set({ merchantOnboarding: { ...onboarding, linkedAccountStatus: 'ACTIVE', settlementStatus: 'ACTIVE', updatedAt: now } }, { merge: true }), stores.docs[0].ref.set({ settlement: { razorpayLinkedAccountId: onboarding.razorpayLinkedAccountId, linkedAccountStatus: 'ACTIVE', settlementStatus: 'ACTIVE', settlementEnabled: true, updatedAt: now } }, { merge: true })]); return { success: true }; }
  async setupDeliveryPayout(uid: string) { const { ref, data } = await this.user(uid); const onboarding = (data.deliveryOnboarding ?? {}) as Record<string, any>; if (onboarding.approvalStatus !== 'APPROVED' || onboarding.kycStatus !== 'VERIFIED') throw new BadRequestException('Delivery KYC must be verified first'); const bank = onboarding.bank; if (!bank?.accountNumber || !bank?.ifsc || !bank?.beneficiaryName) throw new BadRequestException('Bank details are incomplete'); const contact = onboarding.razorpayContactId ? { id: onboarding.razorpayContactId } : await this.payout.createContact({ name: onboarding.legalName ?? data.name ?? '', email: onboarding.email ?? data.email ?? '', phone: onboarding.phone ?? data.phoneNumber ?? '', referenceId: uid }); const fund = onboarding.razorpayFundAccountId ? { id: onboarding.razorpayFundAccountId } : await this.payout.createBankFundAccount({ contactId: contact.id, accountHolderName: bank.beneficiaryName, ifsc: bank.ifsc, accountNumber: bank.accountNumber }); await ref.set({ deliveryOnboarding: { ...onboarding, razorpayContactId: contact.id, razorpayFundAccountId: fund.id, payoutStatus: 'ACTIVE', updatedAt: new Date().toISOString() } }, { merge: true }); return { success: true, payoutStatus: 'ACTIVE' }; }
  private mask(value: any): any { if (!value || typeof value !== 'object') return value; if (Array.isArray(value)) return value.map((item) => this.mask(item)); const result: Record<string, any> = {}; for (const [key, item] of Object.entries(value)) { if (['accountNumber', 'panNumber', 'aadhaarNumber'].includes(key) && typeof item === 'string') result[key] = item.length <= 4 ? item : `****${item.slice(-4)}`; else result[key] = this.mask(item); } return result; }
}
